### ISSUE TITLE
The navigation bar display abnormal when cancel pop with `navigationBarHidden`

### ISSUE THREAD

**Issue by bougieL** [joehinkle11/Lazy-Pop-SwiftUI#5]
- The example code is
```swift
struct Example: View {
    @State var selection = 0
    var body: some View {
        ZStack {
            Color.blue.edgesIgnoringSafeArea(.all)
        }
        .lazyPop()
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .edgesIgnoringSafeArea(.all)
        .navigationBarHidden(true)
    }
}
```
- When swipe half then cancel swipe, the result is
![IMG_0722](https://user-images.githubusercontent.com/36102904/127953131-3955f441-3aec-484f-8256-29a738f08ddb.PNG)

**Comment by joehinkle11** [comment]
Probably related to this issue because you used `edgesIgnoringSafeArea`

https://github.com/joehinkle11/Lazy-Pop-SwiftUI/issues/3#issuecomment-1079688013

**Comment by joehinkle11** [comment]
I was unable to replicate this bug as of Jan 29, 2023. Maybe Apple changed something in SwiftUI's internals which fixed it?
